"""Add VoiceSession and Conversation models

Revision ID: 4ca3268abf85
Revises: 8ddf13406a13
Create Date: 2026-01-24 21:01:08.528357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4ca3268abf85'
down_revision: Union[str, Sequence[str], None] = '8ddf13406a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('stt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_session_session_id'), 'voice_session', ['session_id'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voice_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('assistant_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_voice_session_id'), 'conversation', ['voice_session_id'], unique=True)
    op.create_table('conversation_memory_link',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'memory_id')
    )
    op.create_table('conversation_reminder_link',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'reminder_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_reminder_link')
    op.drop_table('conversation_memory_link')
    op.drop_index(op.f('ix_conversation_voice_session_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_voice_session_session_id'), table_name='voice_session')
    op.drop_table('voice_session')
    # ### end Alembic commands ###
