"""add ai_processing_log table

Revision ID: f0f254b9d37b
Revises: 01ef7eec7bf0
Create Date: 2026-01-31 20:37:43.315864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f0f254b9d37b'
down_revision: Union[str, Sequence[str], None] = '01ef7eec7bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_processing_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('step', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_processing_log_conversation_id'), 'ai_processing_log', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_log_step'), 'ai_processing_log', ['step'], unique=False)
    op.create_index(op.f('ix_ai_processing_log_user_id'), 'ai_processing_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_processing_log_user_id'), table_name='ai_processing_log')
    op.drop_index(op.f('ix_ai_processing_log_step'), table_name='ai_processing_log')
    op.drop_index(op.f('ix_ai_processing_log_conversation_id'), table_name='ai_processing_log')
    op.drop_table('ai_processing_log')
    # ### end Alembic commands ###
