"""Add CASCADE delete to foreign keys

Revision ID: 34dfcde74e2d
Revises: f0f254b9d37b
Create Date: 2026-02-12 19:32:18.386314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '34dfcde74e2d'
down_revision: Union[str, Sequence[str], None] = 'f0f254b9d37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_memory_link_conversation_id_fkey'), 'conversation_memory_link', type_='foreignkey')
    op.drop_constraint(op.f('conversation_memory_link_memory_id_fkey'), 'conversation_memory_link', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_memory_link', 'memory', ['memory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_memory_link', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_reminder_link_conversation_id_fkey'), 'conversation_reminder_link', type_='foreignkey')
    op.drop_constraint(op.f('conversation_reminder_link_reminder_id_fkey'), 'conversation_reminder_link', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_reminder_link', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_reminder_link', 'reminder', ['reminder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reminder_memory_id_fkey'), 'reminder', type_='foreignkey')
    op.create_foreign_key(None, 'reminder', 'memory', ['memory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminder', type_='foreignkey')
    op.create_foreign_key(op.f('reminder_memory_id_fkey'), 'reminder', 'memory', ['memory_id'], ['id'])
    op.drop_constraint(None, 'conversation_reminder_link', type_='foreignkey')
    op.drop_constraint(None, 'conversation_reminder_link', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_reminder_link_reminder_id_fkey'), 'conversation_reminder_link', 'reminder', ['reminder_id'], ['id'])
    op.create_foreign_key(op.f('conversation_reminder_link_conversation_id_fkey'), 'conversation_reminder_link', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversation_memory_link', type_='foreignkey')
    op.drop_constraint(None, 'conversation_memory_link', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_memory_link_memory_id_fkey'), 'conversation_memory_link', 'memory', ['memory_id'], ['id'])
    op.create_foreign_key(op.f('conversation_memory_link_conversation_id_fkey'), 'conversation_memory_link', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
