"""setup helper table

Revision ID: aa85b799a5a3
Revises: 5b8594d0d4bb
Create Date: 2026-01-26 15:42:41.616749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa85b799a5a3'
down_revision: Union[str, Sequence[str], None] = '5b8594d0d4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('social_provider', sa.Enum('GOOGLE', name='socialprovider'), nullable=False),
    sa.Column('social_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('ITEM', 'PLACE', 'SCHEDULE', 'PERSON', 'MEMO', name='memorytype'), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_type'), 'memory', ['type'], unique=False)
    op.create_index(op.f('ix_memory_user_id'), 'memory', ['user_id'], unique=False)
    op.create_table('voice_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('stt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_session_session_id'), 'voice_session', ['session_id'], unique=True)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voice_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('assistant_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_voice_session_id'), 'conversation', ['voice_session_id'], unique=True)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', name='reminderfrequency'), nullable=False),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='reminderstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_memory_id'), 'reminder', ['memory_id'], unique=False)
    op.create_index(op.f('ix_reminder_next_run_at'), 'reminder', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_reminder_status'), 'reminder', ['status'], unique=False)
    op.create_index(op.f('ix_reminder_user_id'), 'reminder', ['user_id'], unique=False)
    op.create_table('conversation_memory_link',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'memory_id')
    )
    op.create_table('conversation_reminder_link',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'reminder_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_reminder_link')
    op.drop_table('conversation_memory_link')
    op.drop_index(op.f('ix_reminder_user_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_status'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_next_run_at'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_memory_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_conversation_voice_session_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_voice_session_session_id'), table_name='voice_session')
    op.drop_table('voice_session')
    op.drop_index(op.f('ix_memory_user_id'), table_name='memory')
    op.drop_index(op.f('ix_memory_type'), table_name='memory')
    op.drop_table('memory')
    op.drop_table('user')
    sa.Enum('ITEM', 'PLACE', 'SCHEDULE', 'PERSON', 'MEMO', name='memorytype').drop(op.get_bind())
    sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', name='reminderfrequency').drop(op.get_bind())
    sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday').drop(op.get_bind())
    sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='reminderstatus').drop(op.get_bind())
    sa.Enum('GOOGLE', name='socialprovider').drop(op.get_bind())
    # ### end Alembic commands ###
